### ISSUE TITLE
Опечатка(копипаста) при выставлении длин ребер графа

### ISSUE THREAD

**Issue by romashok** [AntonCoon/MCMC_bioinf_summer_school_2019#1]
https://github.com/AntonCoon/MCMC_bioinf_summer_school_2019/blob/ef305b628e63fbd733a8ae40c2a5ed570a590a25/3_RevBayes/tree_generator.py#L46-L50

Дублируется *(u, v)*, но нет *(v, u)*.

P.S. Установленные веса не помечаются и перевыставляются: сначала для  *u=v1,v=v2*, потом для  *u=v2,v=v1*.

**Comment by AntonCoon** [comment]
Действительно, дублировалась строка. Спасибо.
